env: prod

app:
  name: payz-sso-service
  version: v0.0.1

server:
  grpc:
    protocol: tcp
    host: 0.0.0.0
    port: 50050
    tls:
      enable: false
      server-cert: ./certs/sso-service.crt
      server-key: ./certs/sso-service.key
      ca-cert: ./certs/ca.crt
      ca-key: ./certs/ca.key
  timeout: 3s

secrets:
  postgres:
    host: localhost
    port: 5432
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    dbname: ${POSTGRES_DBNAME}
    conn-max-idle-time: 30m
    conn-max-lifetime: 5m
    max-idle-conns: 15
    max-open-conns: 5
    sslmode: disable

  jwt: 
    private-key-path: ./jwtRS256.key
    public-key-path: ./jwtRS256.key.pub
    access-ttl: 96h

  redis:
    host: localhost
    port: 6379
    db: ${REDIS_DB}
    user: ${REDIS_USER}
    password: ${REDIS_PASSWORD}
    session-ttl: 168h
    user-ttl: 5m