// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: payment/v1/payment.proto

package paymentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Payment_MakeExTransaction_FullMethodName    = "/payment.v1.Payment/MakeExTransaction"
	Payment_ConfirmExTransaction_FullMethodName = "/payment.v1.Payment/ConfirmExTransaction"
	Payment_CancelExTransaction_FullMethodName  = "/payment.v1.Payment/CancelExTransaction"
	Payment_GetExHistory_FullMethodName         = "/payment.v1.Payment/GetExHistory"
	Payment_GetExTransaction_FullMethodName     = "/payment.v1.Payment/GetExTransaction"
	Payment_GetBalances_FullMethodName          = "/payment.v1.Payment/GetBalances"
)

// PaymentClient is the client API for Payment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentClient interface {
	// Create an ex-transaction
	// REQUIRES: mtls connection
	// METADATA: authorization
	MakeExTransaction(ctx context.Context, in *MakeExRequest, opts ...grpc.CallOption) (*ExTransaction, error)
	// Confirm an ex-transaction
	// REQUIRES: mtls connection
	// METADATA: idempotency-key
	ConfirmExTransaction(ctx context.Context, in *ActionExRequest, opts ...grpc.CallOption) (*ExTransaction, error)
	// Cancel an ex-transaction
	// REQUIRES: mtls connection
	// METADATA: idempotency-key
	CancelExTransaction(ctx context.Context, in *ActionExRequest, opts ...grpc.CallOption) (*ExTransaction, error)
	// Get ex-history
	// REQUIRES: mtls connection
	// METADATA: authorization
	GetExHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*ExHistory, error)
	// Get ex-transaction
	// REQUIRES: mtls connection
	// METADATA: authorization
	GetExTransaction(ctx context.Context, in *GetExRequest, opts ...grpc.CallOption) (*ExTransaction, error)
	// Get balance from crypto
	// REQUIRES: mtls connection
	GetBalances(ctx context.Context, in *GetBalancesRequest, opts ...grpc.CallOption) (*Balances, error)
}

type paymentClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentClient(cc grpc.ClientConnInterface) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) MakeExTransaction(ctx context.Context, in *MakeExRequest, opts ...grpc.CallOption) (*ExTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExTransaction)
	err := c.cc.Invoke(ctx, Payment_MakeExTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) ConfirmExTransaction(ctx context.Context, in *ActionExRequest, opts ...grpc.CallOption) (*ExTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExTransaction)
	err := c.cc.Invoke(ctx, Payment_ConfirmExTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) CancelExTransaction(ctx context.Context, in *ActionExRequest, opts ...grpc.CallOption) (*ExTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExTransaction)
	err := c.cc.Invoke(ctx, Payment_CancelExTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetExHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*ExHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExHistory)
	err := c.cc.Invoke(ctx, Payment_GetExHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetExTransaction(ctx context.Context, in *GetExRequest, opts ...grpc.CallOption) (*ExTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExTransaction)
	err := c.cc.Invoke(ctx, Payment_GetExTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetBalances(ctx context.Context, in *GetBalancesRequest, opts ...grpc.CallOption) (*Balances, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Balances)
	err := c.cc.Invoke(ctx, Payment_GetBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServer is the server API for Payment service.
// All implementations must embed UnimplementedPaymentServer
// for forward compatibility.
type PaymentServer interface {
	// Create an ex-transaction
	// REQUIRES: mtls connection
	// METADATA: authorization
	MakeExTransaction(context.Context, *MakeExRequest) (*ExTransaction, error)
	// Confirm an ex-transaction
	// REQUIRES: mtls connection
	// METADATA: idempotency-key
	ConfirmExTransaction(context.Context, *ActionExRequest) (*ExTransaction, error)
	// Cancel an ex-transaction
	// REQUIRES: mtls connection
	// METADATA: idempotency-key
	CancelExTransaction(context.Context, *ActionExRequest) (*ExTransaction, error)
	// Get ex-history
	// REQUIRES: mtls connection
	// METADATA: authorization
	GetExHistory(context.Context, *GetHistoryRequest) (*ExHistory, error)
	// Get ex-transaction
	// REQUIRES: mtls connection
	// METADATA: authorization
	GetExTransaction(context.Context, *GetExRequest) (*ExTransaction, error)
	// Get balance from crypto
	// REQUIRES: mtls connection
	GetBalances(context.Context, *GetBalancesRequest) (*Balances, error)
	mustEmbedUnimplementedPaymentServer()
}

// UnimplementedPaymentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServer struct{}

func (UnimplementedPaymentServer) MakeExTransaction(context.Context, *MakeExRequest) (*ExTransaction, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeExTransaction not implemented")
}
func (UnimplementedPaymentServer) ConfirmExTransaction(context.Context, *ActionExRequest) (*ExTransaction, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmExTransaction not implemented")
}
func (UnimplementedPaymentServer) CancelExTransaction(context.Context, *ActionExRequest) (*ExTransaction, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelExTransaction not implemented")
}
func (UnimplementedPaymentServer) GetExHistory(context.Context, *GetHistoryRequest) (*ExHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExHistory not implemented")
}
func (UnimplementedPaymentServer) GetExTransaction(context.Context, *GetExRequest) (*ExTransaction, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExTransaction not implemented")
}
func (UnimplementedPaymentServer) GetBalances(context.Context, *GetBalancesRequest) (*Balances, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalances not implemented")
}
func (UnimplementedPaymentServer) mustEmbedUnimplementedPaymentServer() {}
func (UnimplementedPaymentServer) testEmbeddedByValue()                 {}

// UnsafePaymentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServer will
// result in compilation errors.
type UnsafePaymentServer interface {
	mustEmbedUnimplementedPaymentServer()
}

func RegisterPaymentServer(s grpc.ServiceRegistrar, srv PaymentServer) {
	// If the following call panics, it indicates UnimplementedPaymentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Payment_ServiceDesc, srv)
}

func _Payment_MakeExTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeExRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).MakeExTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_MakeExTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).MakeExTransaction(ctx, req.(*MakeExRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_ConfirmExTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionExRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ConfirmExTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_ConfirmExTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ConfirmExTransaction(ctx, req.(*ActionExRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_CancelExTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionExRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CancelExTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_CancelExTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CancelExTransaction(ctx, req.(*ActionExRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetExHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetExHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_GetExHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetExHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetExTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetExTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_GetExTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetExTransaction(ctx, req.(*GetExRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_GetBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetBalances(ctx, req.(*GetBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Payment_ServiceDesc is the grpc.ServiceDesc for Payment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeExTransaction",
			Handler:    _Payment_MakeExTransaction_Handler,
		},
		{
			MethodName: "ConfirmExTransaction",
			Handler:    _Payment_ConfirmExTransaction_Handler,
		},
		{
			MethodName: "CancelExTransaction",
			Handler:    _Payment_CancelExTransaction_Handler,
		},
		{
			MethodName: "GetExHistory",
			Handler:    _Payment_GetExHistory_Handler,
		},
		{
			MethodName: "GetExTransaction",
			Handler:    _Payment_GetExTransaction_Handler,
		},
		{
			MethodName: "GetBalances",
			Handler:    _Payment_GetBalances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/v1/payment.proto",
}
