// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: shop/v1/shop.proto

package shoppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShopService_CreateShop_FullMethodName       = "/shopv1.ShopService/CreateShop"
	ShopService_GetShopByOwner_FullMethodName   = "/shopv1.ShopService/GetShopByOwner"
	ShopService_GetShopsByUserID_FullMethodName = "/shopv1.ShopService/GetShopsByUserID"
	ShopService_UpdateShopByID_FullMethodName   = "/shopv1.ShopService/UpdateShopByID"
	ShopService_DeleteShopByID_FullMethodName   = "/shopv1.ShopService/DeleteShopByID"
)

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopServiceClient interface {
	CreateShop(ctx context.Context, in *CreateShopReq, opts ...grpc.CallOption) (*CreateShopResp, error)
	GetShopByOwner(ctx context.Context, in *GetShopByOwnerReq, opts ...grpc.CallOption) (*GetShopByOwnerResp, error)
	GetShopsByUserID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetShopsByUserIDResp, error)
	UpdateShopByID(ctx context.Context, in *UpdateShopByIDReq, opts ...grpc.CallOption) (*UpdateShopByIDResp, error)
	DeleteShopByID(ctx context.Context, in *DeleteShopByIDReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type shopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopServiceClient(cc grpc.ClientConnInterface) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) CreateShop(ctx context.Context, in *CreateShopReq, opts ...grpc.CallOption) (*CreateShopResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShopResp)
	err := c.cc.Invoke(ctx, ShopService_CreateShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetShopByOwner(ctx context.Context, in *GetShopByOwnerReq, opts ...grpc.CallOption) (*GetShopByOwnerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShopByOwnerResp)
	err := c.cc.Invoke(ctx, ShopService_GetShopByOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetShopsByUserID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetShopsByUserIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShopsByUserIDResp)
	err := c.cc.Invoke(ctx, ShopService_GetShopsByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UpdateShopByID(ctx context.Context, in *UpdateShopByIDReq, opts ...grpc.CallOption) (*UpdateShopByIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateShopByIDResp)
	err := c.cc.Invoke(ctx, ShopService_UpdateShopByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) DeleteShopByID(ctx context.Context, in *DeleteShopByIDReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShopService_DeleteShopByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
// All implementations must embed UnimplementedShopServiceServer
// for forward compatibility.
type ShopServiceServer interface {
	CreateShop(context.Context, *CreateShopReq) (*CreateShopResp, error)
	GetShopByOwner(context.Context, *GetShopByOwnerReq) (*GetShopByOwnerResp, error)
	GetShopsByUserID(context.Context, *emptypb.Empty) (*GetShopsByUserIDResp, error)
	UpdateShopByID(context.Context, *UpdateShopByIDReq) (*UpdateShopByIDResp, error)
	DeleteShopByID(context.Context, *DeleteShopByIDReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedShopServiceServer()
}

// UnimplementedShopServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShopServiceServer struct{}

func (UnimplementedShopServiceServer) CreateShop(context.Context, *CreateShopReq) (*CreateShopResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShop not implemented")
}
func (UnimplementedShopServiceServer) GetShopByOwner(context.Context, *GetShopByOwnerReq) (*GetShopByOwnerResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShopByOwner not implemented")
}
func (UnimplementedShopServiceServer) GetShopsByUserID(context.Context, *emptypb.Empty) (*GetShopsByUserIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShopsByUserID not implemented")
}
func (UnimplementedShopServiceServer) UpdateShopByID(context.Context, *UpdateShopByIDReq) (*UpdateShopByIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShopByID not implemented")
}
func (UnimplementedShopServiceServer) DeleteShopByID(context.Context, *DeleteShopByIDReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShopByID not implemented")
}
func (UnimplementedShopServiceServer) mustEmbedUnimplementedShopServiceServer() {}
func (UnimplementedShopServiceServer) testEmbeddedByValue()                     {}

// UnsafeShopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopServiceServer will
// result in compilation errors.
type UnsafeShopServiceServer interface {
	mustEmbedUnimplementedShopServiceServer()
}

func RegisterShopServiceServer(s grpc.ServiceRegistrar, srv ShopServiceServer) {
	// If the following call panics, it indicates UnimplementedShopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShopService_ServiceDesc, srv)
}

func _ShopService_CreateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).CreateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_CreateShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).CreateShop(ctx, req.(*CreateShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetShopByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopByOwnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetShopByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetShopByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetShopByOwner(ctx, req.(*GetShopByOwnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetShopsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetShopsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetShopsByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetShopsByUserID(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UpdateShopByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShopByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).UpdateShopByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_UpdateShopByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).UpdateShopByID(ctx, req.(*UpdateShopByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_DeleteShopByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShopByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).DeleteShopByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_DeleteShopByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).DeleteShopByID(ctx, req.(*DeleteShopByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopService_ServiceDesc is the grpc.ServiceDesc for ShopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shopv1.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShop",
			Handler:    _ShopService_CreateShop_Handler,
		},
		{
			MethodName: "GetShopByOwner",
			Handler:    _ShopService_GetShopByOwner_Handler,
		},
		{
			MethodName: "GetShopsByUserID",
			Handler:    _ShopService_GetShopsByUserID_Handler,
		},
		{
			MethodName: "UpdateShopByID",
			Handler:    _ShopService_UpdateShopByID_Handler,
		},
		{
			MethodName: "DeleteShopByID",
			Handler:    _ShopService_DeleteShopByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop/v1/shop.proto",
}
