// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: shop/v1/shop.proto

package shoppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shop) Reset() {
	*x = Shop{}
	mi := &file_shop_v1_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{0}
}

func (x *Shop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shop) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Shop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateShopReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShopReq) Reset() {
	*x = CreateShopReq{}
	mi := &file_shop_v1_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopReq) ProtoMessage() {}

func (x *CreateShopReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopReq.ProtoReflect.Descriptor instead.
func (*CreateShopReq) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShopReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateShopResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *Shop                  `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShopResp) Reset() {
	*x = CreateShopResp{}
	mi := &file_shop_v1_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShopResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopResp) ProtoMessage() {}

func (x *CreateShopResp) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopResp.ProtoReflect.Descriptor instead.
func (*CreateShopResp) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShopResp) GetShop() *Shop {
	if x != nil {
		return x.Shop
	}
	return nil
}

type GetShopByOwnerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopByOwnerReq) Reset() {
	*x = GetShopByOwnerReq{}
	mi := &file_shop_v1_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopByOwnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopByOwnerReq) ProtoMessage() {}

func (x *GetShopByOwnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopByOwnerReq.ProtoReflect.Descriptor instead.
func (*GetShopByOwnerReq) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{3}
}

func (x *GetShopByOwnerReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetShopByOwnerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *Shop                  `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopByOwnerResp) Reset() {
	*x = GetShopByOwnerResp{}
	mi := &file_shop_v1_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopByOwnerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopByOwnerResp) ProtoMessage() {}

func (x *GetShopByOwnerResp) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopByOwnerResp.ProtoReflect.Descriptor instead.
func (*GetShopByOwnerResp) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{4}
}

func (x *GetShopByOwnerResp) GetShop() *Shop {
	if x != nil {
		return x.Shop
	}
	return nil
}

type GetShopsByUserIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shops         []*Shop                `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopsByUserIDResp) Reset() {
	*x = GetShopsByUserIDResp{}
	mi := &file_shop_v1_shop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopsByUserIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopsByUserIDResp) ProtoMessage() {}

func (x *GetShopsByUserIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopsByUserIDResp.ProtoReflect.Descriptor instead.
func (*GetShopsByUserIDResp) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{5}
}

func (x *GetShopsByUserIDResp) GetShops() []*Shop {
	if x != nil {
		return x.Shops
	}
	return nil
}

type UpdateShopByIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShopByIDReq) Reset() {
	*x = UpdateShopByIDReq{}
	mi := &file_shop_v1_shop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShopByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShopByIDReq) ProtoMessage() {}

func (x *UpdateShopByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShopByIDReq.ProtoReflect.Descriptor instead.
func (*UpdateShopByIDReq) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateShopByIDReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateShopByIDReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateShopByIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *Shop                  `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShopByIDResp) Reset() {
	*x = UpdateShopByIDResp{}
	mi := &file_shop_v1_shop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShopByIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShopByIDResp) ProtoMessage() {}

func (x *UpdateShopByIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShopByIDResp.ProtoReflect.Descriptor instead.
func (*UpdateShopByIDResp) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateShopByIDResp) GetShop() *Shop {
	if x != nil {
		return x.Shop
	}
	return nil
}

type DeleteShopByIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShopByIDReq) Reset() {
	*x = DeleteShopByIDReq{}
	mi := &file_shop_v1_shop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShopByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShopByIDReq) ProtoMessage() {}

func (x *DeleteShopByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShopByIDReq.ProtoReflect.Descriptor instead.
func (*DeleteShopByIDReq) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteShopByIDReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_shop_v1_shop_proto protoreflect.FileDescriptor

const file_shop_v1_shop_proto_rawDesc = "" +
	"\n" +
	"\x12shop/v1/shop.proto\x12\x06shopv1\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\x04Shop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"#\n" +
	"\rCreateShopReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"2\n" +
	"\x0eCreateShopResp\x12 \n" +
	"\x04shop\x18\x01 \x01(\v2\f.shopv1.ShopR\x04shop\"#\n" +
	"\x11GetShopByOwnerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x12GetShopByOwnerResp\x12 \n" +
	"\x04shop\x18\x01 \x01(\v2\f.shopv1.ShopR\x04shop\":\n" +
	"\x14GetShopsByUserIDResp\x12\"\n" +
	"\x05shops\x18\x01 \x03(\v2\f.shopv1.ShopR\x05shops\"7\n" +
	"\x11UpdateShopByIDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\x12UpdateShopByIDResp\x12 \n" +
	"\x04shop\x18\x01 \x01(\v2\f.shopv1.ShopR\x04shop\"#\n" +
	"\x11DeleteShopByIDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xeb\x02\n" +
	"\vShopService\x12;\n" +
	"\n" +
	"CreateShop\x12\x15.shopv1.CreateShopReq\x1a\x16.shopv1.CreateShopResp\x12G\n" +
	"\x0eGetShopByOwner\x12\x19.shopv1.GetShopByOwnerReq\x1a\x1a.shopv1.GetShopByOwnerResp\x12H\n" +
	"\x10GetShopsByUserID\x12\x16.google.protobuf.Empty\x1a\x1c.shopv1.GetShopsByUserIDResp\x12G\n" +
	"\x0eUpdateShopByID\x12\x19.shopv1.UpdateShopByIDReq\x1a\x1a.shopv1.UpdateShopByIDResp\x12C\n" +
	"\x0eDeleteShopByID\x12\x19.shopv1.DeleteShopByIDReq\x1a\x16.google.protobuf.EmptyB&Z$github.com/cnt-payz/payz/shop;shoppbb\x06proto3"

var (
	file_shop_v1_shop_proto_rawDescOnce sync.Once
	file_shop_v1_shop_proto_rawDescData []byte
)

func file_shop_v1_shop_proto_rawDescGZIP() []byte {
	file_shop_v1_shop_proto_rawDescOnce.Do(func() {
		file_shop_v1_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_v1_shop_proto_rawDesc), len(file_shop_v1_shop_proto_rawDesc)))
	})
	return file_shop_v1_shop_proto_rawDescData
}

var file_shop_v1_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_shop_v1_shop_proto_goTypes = []any{
	(*Shop)(nil),                 // 0: shopv1.Shop
	(*CreateShopReq)(nil),        // 1: shopv1.CreateShopReq
	(*CreateShopResp)(nil),       // 2: shopv1.CreateShopResp
	(*GetShopByOwnerReq)(nil),    // 3: shopv1.GetShopByOwnerReq
	(*GetShopByOwnerResp)(nil),   // 4: shopv1.GetShopByOwnerResp
	(*GetShopsByUserIDResp)(nil), // 5: shopv1.GetShopsByUserIDResp
	(*UpdateShopByIDReq)(nil),    // 6: shopv1.UpdateShopByIDReq
	(*UpdateShopByIDResp)(nil),   // 7: shopv1.UpdateShopByIDResp
	(*DeleteShopByIDReq)(nil),    // 8: shopv1.DeleteShopByIDReq
	(*emptypb.Empty)(nil),        // 9: google.protobuf.Empty
}
var file_shop_v1_shop_proto_depIdxs = []int32{
	0, // 0: shopv1.CreateShopResp.shop:type_name -> shopv1.Shop
	0, // 1: shopv1.GetShopByOwnerResp.shop:type_name -> shopv1.Shop
	0, // 2: shopv1.GetShopsByUserIDResp.shops:type_name -> shopv1.Shop
	0, // 3: shopv1.UpdateShopByIDResp.shop:type_name -> shopv1.Shop
	1, // 4: shopv1.ShopService.CreateShop:input_type -> shopv1.CreateShopReq
	3, // 5: shopv1.ShopService.GetShopByOwner:input_type -> shopv1.GetShopByOwnerReq
	9, // 6: shopv1.ShopService.GetShopsByUserID:input_type -> google.protobuf.Empty
	6, // 7: shopv1.ShopService.UpdateShopByID:input_type -> shopv1.UpdateShopByIDReq
	8, // 8: shopv1.ShopService.DeleteShopByID:input_type -> shopv1.DeleteShopByIDReq
	2, // 9: shopv1.ShopService.CreateShop:output_type -> shopv1.CreateShopResp
	4, // 10: shopv1.ShopService.GetShopByOwner:output_type -> shopv1.GetShopByOwnerResp
	5, // 11: shopv1.ShopService.GetShopsByUserID:output_type -> shopv1.GetShopsByUserIDResp
	7, // 12: shopv1.ShopService.UpdateShopByID:output_type -> shopv1.UpdateShopByIDResp
	9, // 13: shopv1.ShopService.DeleteShopByID:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shop_v1_shop_proto_init() }
func file_shop_v1_shop_proto_init() {
	if File_shop_v1_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_v1_shop_proto_rawDesc), len(file_shop_v1_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_v1_shop_proto_goTypes,
		DependencyIndexes: file_shop_v1_shop_proto_depIdxs,
		MessageInfos:      file_shop_v1_shop_proto_msgTypes,
	}.Build()
	File_shop_v1_shop_proto = out.File
	file_shop_v1_shop_proto_goTypes = nil
	file_shop_v1_shop_proto_depIdxs = nil
}
