// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: payment/v1/payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN  Status = 0
	Status_STATUS_PENDING  Status = 1
	Status_STATUS_SUCCESS  Status = 2
	Status_STATUS_CANCELED Status = 3
	Status_STATUS_DEADLINE Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_PENDING",
		2: "STATUS_SUCCESS",
		3: "STATUS_CANCELED",
		4: "STATUS_DEADLINE",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN":  0,
		"STATUS_PENDING":  1,
		"STATUS_SUCCESS":  2,
		"STATUS_CANCELED": 3,
		"STATUS_DEADLINE": 4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_payment_v1_payment_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

type Typ int32

const (
	Typ_TYPE_UNKNOWN  Typ = 0
	Typ_TYPE_DEPOSIT  Typ = 1
	Typ_TYPE_WITHDRAW Typ = 2
)

// Enum value maps for Typ.
var (
	Typ_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_DEPOSIT",
		2: "TYPE_WITHDRAW",
	}
	Typ_value = map[string]int32{
		"TYPE_UNKNOWN":  0,
		"TYPE_DEPOSIT":  1,
		"TYPE_WITHDRAW": 2,
	}
)

func (x Typ) Enum() *Typ {
	p := new(Typ)
	*p = x
	return p
}

func (x Typ) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Typ) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_v1_payment_proto_enumTypes[1].Descriptor()
}

func (Typ) Type() protoreflect.EnumType {
	return &file_payment_v1_payment_proto_enumTypes[1]
}

func (x Typ) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Typ.Descriptor instead.
func (Typ) EnumDescriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"` //  "1000000" = 1usdt
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Amount) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// Domain model of ex-transaction
type ExTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=payment.v1.Status" json:"status,omitempty"`
	Typ           Typ                    `protobuf:"varint,5,opt,name=typ,proto3,enum=payment.v1.Typ" json:"typ,omitempty"`
	Amount        *Amount                `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,7,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	UserMetadata  *structpb.Struct       `protobuf:"bytes,8,opt,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExTransaction) Reset() {
	*x = ExTransaction{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExTransaction) ProtoMessage() {}

func (x *ExTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExTransaction.ProtoReflect.Descriptor instead.
func (*ExTransaction) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ExTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExTransaction) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *ExTransaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExTransaction) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *ExTransaction) GetTyp() Typ {
	if x != nil {
		return x.Typ
	}
	return Typ_TYPE_UNKNOWN
}

func (x *ExTransaction) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *ExTransaction) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *ExTransaction) GetUserMetadata() *structpb.Struct {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

func (x *ExTransaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExTransaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ExHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*ExTransaction       `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExHistory) Reset() {
	*x = ExHistory{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExHistory) ProtoMessage() {}

func (x *ExHistory) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExHistory.ProtoReflect.Descriptor instead.
func (*ExHistory) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *ExHistory) GetTransactions() []*ExTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ExHistory) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Balances struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frozen        string                 `protobuf:"bytes,1,opt,name=frozen,proto3" json:"frozen,omitempty"`
	General       string                 `protobuf:"bytes,2,opt,name=general,proto3" json:"general,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balances) Reset() {
	*x = Balances{}
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balances) ProtoMessage() {}

func (x *Balances) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balances.ProtoReflect.Descriptor instead.
func (*Balances) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *Balances) GetFrozen() string {
	if x != nil {
		return x.Frozen
	}
	return ""
}

func (x *Balances) GetGeneral() string {
	if x != nil {
		return x.General
	}
	return ""
}

type MakeExResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *ExTransaction         `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	TargetAddress string                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeExResponse) Reset() {
	*x = MakeExResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeExResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeExResponse) ProtoMessage() {}

func (x *MakeExResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeExResponse.ProtoReflect.Descriptor instead.
func (*MakeExResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *MakeExResponse) GetTransaction() *ExTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *MakeExResponse) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

type MakeExRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Typ           Typ                    `protobuf:"varint,2,opt,name=typ,proto3,enum=payment.v1.Typ" json:"typ,omitempty"`
	Amount        *Amount                `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,4,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	UserMetadata  *structpb.Struct       `protobuf:"bytes,5,opt,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	Singature     string                 `protobuf:"bytes,6,opt,name=singature,proto3" json:"singature,omitempty"` // timestamp:shop_id:private_key -> sha256
	TargetAddress string                 `protobuf:"bytes,7,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeExRequest) Reset() {
	*x = MakeExRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeExRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeExRequest) ProtoMessage() {}

func (x *MakeExRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeExRequest.ProtoReflect.Descriptor instead.
func (*MakeExRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *MakeExRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *MakeExRequest) GetTyp() Typ {
	if x != nil {
		return x.Typ
	}
	return Typ_TYPE_UNKNOWN
}

func (x *MakeExRequest) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *MakeExRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *MakeExRequest) GetUserMetadata() *structpb.Struct {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

func (x *MakeExRequest) GetSingature() string {
	if x != nil {
		return x.Singature
	}
	return ""
}

func (x *MakeExRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *MakeExRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ActionExRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // timestamp:shop_id:private_key -> sha256
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionExRequest) Reset() {
	*x = ActionExRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionExRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionExRequest) ProtoMessage() {}

func (x *ActionExRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionExRequest.ProtoReflect.Descriptor instead.
func (*ActionExRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ActionExRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ActionExRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ActionExRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ShopId        string                 `protobuf:"bytes,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *GetHistoryRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHistoryRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetHistoryRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

type GetExRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExRequest) Reset() {
	*x = GetExRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExRequest) ProtoMessage() {}

func (x *GetExRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExRequest.ProtoReflect.Descriptor instead.
func (*GetExRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetExRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesRequest) Reset() {
	*x = GetBalancesRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesRequest) ProtoMessage() {}

func (x *GetBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetBalancesRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *GetBalancesRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\n" +
	"payment.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\" \n" +
	"\x06Amount\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\"\xa9\x03\n" +
	"\rExTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.payment.v1.StatusR\x06status\x12!\n" +
	"\x03typ\x18\x05 \x01(\x0e2\x0f.payment.v1.TypR\x03typ\x12*\n" +
	"\x06amount\x18\x06 \x01(\v2\x12.payment.v1.AmountR\x06amount\x12!\n" +
	"\fcallback_url\x18\a \x01(\tR\vcallbackUrl\x12<\n" +
	"\ruser_metadata\x18\b \x01(\v2\x17.google.protobuf.StructR\fuserMetadata\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtJ\x04\b\v\x10\x10\"\x84\x01\n" +
	"\tExHistory\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.payment.v1.ExTransactionR\ftransactions\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"<\n" +
	"\bBalances\x12\x16\n" +
	"\x06frozen\x18\x01 \x01(\tR\x06frozen\x12\x18\n" +
	"\ageneral\x18\x02 \x01(\tR\ageneral\"t\n" +
	"\x0eMakeExResponse\x12;\n" +
	"\vtransaction\x18\x01 \x01(\v2\x19.payment.v1.ExTransactionR\vtransaction\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\tR\rtargetAddress\"\xd7\x02\n" +
	"\rMakeExRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12!\n" +
	"\x03typ\x18\x02 \x01(\x0e2\x0f.payment.v1.TypR\x03typ\x12*\n" +
	"\x06amount\x18\x03 \x01(\v2\x12.payment.v1.AmountR\x06amount\x12!\n" +
	"\fcallback_url\x18\x04 \x01(\tR\vcallbackUrl\x12<\n" +
	"\ruser_metadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\fuserMetadata\x12\x1c\n" +
	"\tsingature\x18\x06 \x01(\tR\tsingature\x12%\n" +
	"\x0etarget_address\x18\a \x01(\tR\rtargetAddress\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x90\x01\n" +
	"\x0fActionExRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"T\n" +
	"\x11GetHistoryRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x17\n" +
	"\ashop_id\x18\x03 \x01(\tR\x06shopId\"5\n" +
	"\fGetExRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"-\n" +
	"\x12GetBalancesRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId*n\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x02\x12\x13\n" +
	"\x0fSTATUS_CANCELED\x10\x03\x12\x13\n" +
	"\x0fSTATUS_DEADLINE\x10\x04*<\n" +
	"\x03Typ\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fTYPE_DEPOSIT\x10\x01\x12\x11\n" +
	"\rTYPE_WITHDRAW\x10\x022\xc8\x03\n" +
	"\aPayment\x12J\n" +
	"\x11MakeExTransaction\x12\x19.payment.v1.MakeExRequest\x1a\x1a.payment.v1.MakeExResponse\x12N\n" +
	"\x14ConfirmExTransaction\x12\x1b.payment.v1.ActionExRequest\x1a\x19.payment.v1.ExTransaction\x12M\n" +
	"\x13CancelExTransaction\x12\x1b.payment.v1.ActionExRequest\x1a\x19.payment.v1.ExTransaction\x12D\n" +
	"\fGetExHistory\x12\x1d.payment.v1.GetHistoryRequest\x1a\x15.payment.v1.ExHistory\x12G\n" +
	"\x10GetExTransaction\x12\x18.payment.v1.GetExRequest\x1a\x19.payment.v1.ExTransaction\x12C\n" +
	"\vGetBalances\x12\x1e.payment.v1.GetBalancesRequest\x1a\x14.payment.v1.BalancesB-Z+github.com/cnt-payz/payz/payment; paymentpbb\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_payment_v1_payment_proto_goTypes = []any{
	(Status)(0),                   // 0: payment.v1.Status
	(Typ)(0),                      // 1: payment.v1.Typ
	(*Amount)(nil),                // 2: payment.v1.Amount
	(*ExTransaction)(nil),         // 3: payment.v1.ExTransaction
	(*ExHistory)(nil),             // 4: payment.v1.ExHistory
	(*Balances)(nil),              // 5: payment.v1.Balances
	(*MakeExResponse)(nil),        // 6: payment.v1.MakeExResponse
	(*MakeExRequest)(nil),         // 7: payment.v1.MakeExRequest
	(*ActionExRequest)(nil),       // 8: payment.v1.ActionExRequest
	(*GetHistoryRequest)(nil),     // 9: payment.v1.GetHistoryRequest
	(*GetExRequest)(nil),          // 10: payment.v1.GetExRequest
	(*GetBalancesRequest)(nil),    // 11: payment.v1.GetBalancesRequest
	(*structpb.Struct)(nil),       // 12: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	0,  // 0: payment.v1.ExTransaction.status:type_name -> payment.v1.Status
	1,  // 1: payment.v1.ExTransaction.typ:type_name -> payment.v1.Typ
	2,  // 2: payment.v1.ExTransaction.amount:type_name -> payment.v1.Amount
	12, // 3: payment.v1.ExTransaction.user_metadata:type_name -> google.protobuf.Struct
	13, // 4: payment.v1.ExTransaction.created_at:type_name -> google.protobuf.Timestamp
	13, // 5: payment.v1.ExTransaction.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 6: payment.v1.ExHistory.transactions:type_name -> payment.v1.ExTransaction
	13, // 7: payment.v1.ExHistory.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 8: payment.v1.MakeExResponse.transaction:type_name -> payment.v1.ExTransaction
	1,  // 9: payment.v1.MakeExRequest.typ:type_name -> payment.v1.Typ
	2,  // 10: payment.v1.MakeExRequest.amount:type_name -> payment.v1.Amount
	12, // 11: payment.v1.MakeExRequest.user_metadata:type_name -> google.protobuf.Struct
	13, // 12: payment.v1.MakeExRequest.timestamp:type_name -> google.protobuf.Timestamp
	13, // 13: payment.v1.ActionExRequest.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 14: payment.v1.Payment.MakeExTransaction:input_type -> payment.v1.MakeExRequest
	8,  // 15: payment.v1.Payment.ConfirmExTransaction:input_type -> payment.v1.ActionExRequest
	8,  // 16: payment.v1.Payment.CancelExTransaction:input_type -> payment.v1.ActionExRequest
	9,  // 17: payment.v1.Payment.GetExHistory:input_type -> payment.v1.GetHistoryRequest
	10, // 18: payment.v1.Payment.GetExTransaction:input_type -> payment.v1.GetExRequest
	11, // 19: payment.v1.Payment.GetBalances:input_type -> payment.v1.GetBalancesRequest
	6,  // 20: payment.v1.Payment.MakeExTransaction:output_type -> payment.v1.MakeExResponse
	3,  // 21: payment.v1.Payment.ConfirmExTransaction:output_type -> payment.v1.ExTransaction
	3,  // 22: payment.v1.Payment.CancelExTransaction:output_type -> payment.v1.ExTransaction
	4,  // 23: payment.v1.Payment.GetExHistory:output_type -> payment.v1.ExHistory
	3,  // 24: payment.v1.Payment.GetExTransaction:output_type -> payment.v1.ExTransaction
	5,  // 25: payment.v1.Payment.GetBalances:output_type -> payment.v1.Balances
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
