// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: sso/v1/sso.proto

package ssopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Domain model of session
type Token struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Access           string                 `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	Refresh          string                 `protobuf:"bytes,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
	AccessExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=access_expires_at,json=accessExpiresAt,proto3" json:"access_expires_at,omitempty"`
	RefreshExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=refresh_expires_at,json=refreshExpiresAt,proto3" json:"refresh_expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_sso_v1_sso_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_sso_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_sso_v1_sso_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *Token) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

func (x *Token) GetAccessExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessExpiresAt
	}
	return nil
}

func (x *Token) GetRefreshExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshExpiresAt
	}
	return nil
}

// Domain model of user
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_sso_v1_sso_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_sso_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_sso_v1_sso_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_sso_v1_sso_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_sso_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_sso_v1_sso_proto_rawDescGZIP(), []int{2}
}

func (x *PublicKey) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_sso_v1_sso_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_sso_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_sso_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_sso_v1_sso_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_sso_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_sso_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_sso_v1_sso_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_sso_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_sso_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_sso_v1_sso_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_sso_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_sso_proto_rawDescGZIP(), []int{6}
}

func (x *GetByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByEmailRequest) Reset() {
	*x = GetByEmailRequest{}
	mi := &file_sso_v1_sso_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByEmailRequest) ProtoMessage() {}

func (x *GetByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_sso_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetByEmailRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_sso_proto_rawDescGZIP(), []int{7}
}

func (x *GetByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_sso_v1_sso_proto protoreflect.FileDescriptor

const file_sso_v1_sso_proto_rawDesc = "" +
	"\n" +
	"\x10sso/v1/sso.proto\x12\x06sso.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd1\x01\n" +
	"\x05Token\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\x12\x18\n" +
	"\arefresh\x18\x02 \x01(\tR\arefresh\x12F\n" +
	"\x11access_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0faccessExpiresAt\x12H\n" +
	"\x12refresh_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10refreshExpiresAtJ\x04\b\x05\x10\v\"m\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtJ\x04\b\x04\x10\v\"\x1f\n" +
	"\tPublicKey\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\")\n" +
	"\x0eGetByIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\")\n" +
	"\x11GetByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email2\xf0\x03\n" +
	"\x03SSO\x12,\n" +
	"\x05Login\x12\x14.sso.v1.LoginRequest\x1a\r.sso.v1.Token\x122\n" +
	"\bRegister\x12\x17.sso.v1.RegisterRequest\x1a\r.sso.v1.Token\x120\n" +
	"\aRefresh\x12\x16.sso.v1.RefreshRequest\x1a\r.sso.v1.Token\x12;\n" +
	"\tLogoutAll\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x128\n" +
	"\x06Delete\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x123\n" +
	"\vGetUserByID\x12\x16.sso.v1.GetByIDRequest\x1a\f.sso.v1.User\x129\n" +
	"\x0eGetUserByEmail\x12\x19.sso.v1.GetByEmailRequest\x1a\f.sso.v1.User\x123\n" +
	"\vGetSelfUser\x12\x16.google.protobuf.Empty\x1a\f.sso.v1.User\x129\n" +
	"\fGetPublicKey\x12\x16.google.protobuf.Empty\x1a\x11.sso.v1.PublicKeyB%Z#github.com/cnt-payz/payz/sso; ssopbb\x06proto3"

var (
	file_sso_v1_sso_proto_rawDescOnce sync.Once
	file_sso_v1_sso_proto_rawDescData []byte
)

func file_sso_v1_sso_proto_rawDescGZIP() []byte {
	file_sso_v1_sso_proto_rawDescOnce.Do(func() {
		file_sso_v1_sso_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sso_v1_sso_proto_rawDesc), len(file_sso_v1_sso_proto_rawDesc)))
	})
	return file_sso_v1_sso_proto_rawDescData
}

var file_sso_v1_sso_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sso_v1_sso_proto_goTypes = []any{
	(*Token)(nil),                 // 0: sso.v1.Token
	(*User)(nil),                  // 1: sso.v1.User
	(*PublicKey)(nil),             // 2: sso.v1.PublicKey
	(*LoginRequest)(nil),          // 3: sso.v1.LoginRequest
	(*RegisterRequest)(nil),       // 4: sso.v1.RegisterRequest
	(*RefreshRequest)(nil),        // 5: sso.v1.RefreshRequest
	(*GetByIDRequest)(nil),        // 6: sso.v1.GetByIDRequest
	(*GetByEmailRequest)(nil),     // 7: sso.v1.GetByEmailRequest
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_sso_v1_sso_proto_depIdxs = []int32{
	8,  // 0: sso.v1.Token.access_expires_at:type_name -> google.protobuf.Timestamp
	8,  // 1: sso.v1.Token.refresh_expires_at:type_name -> google.protobuf.Timestamp
	8,  // 2: sso.v1.User.created_at:type_name -> google.protobuf.Timestamp
	3,  // 3: sso.v1.SSO.Login:input_type -> sso.v1.LoginRequest
	4,  // 4: sso.v1.SSO.Register:input_type -> sso.v1.RegisterRequest
	5,  // 5: sso.v1.SSO.Refresh:input_type -> sso.v1.RefreshRequest
	9,  // 6: sso.v1.SSO.LogoutAll:input_type -> google.protobuf.Empty
	9,  // 7: sso.v1.SSO.Delete:input_type -> google.protobuf.Empty
	6,  // 8: sso.v1.SSO.GetUserByID:input_type -> sso.v1.GetByIDRequest
	7,  // 9: sso.v1.SSO.GetUserByEmail:input_type -> sso.v1.GetByEmailRequest
	9,  // 10: sso.v1.SSO.GetSelfUser:input_type -> google.protobuf.Empty
	9,  // 11: sso.v1.SSO.GetPublicKey:input_type -> google.protobuf.Empty
	0,  // 12: sso.v1.SSO.Login:output_type -> sso.v1.Token
	0,  // 13: sso.v1.SSO.Register:output_type -> sso.v1.Token
	0,  // 14: sso.v1.SSO.Refresh:output_type -> sso.v1.Token
	9,  // 15: sso.v1.SSO.LogoutAll:output_type -> google.protobuf.Empty
	9,  // 16: sso.v1.SSO.Delete:output_type -> google.protobuf.Empty
	1,  // 17: sso.v1.SSO.GetUserByID:output_type -> sso.v1.User
	1,  // 18: sso.v1.SSO.GetUserByEmail:output_type -> sso.v1.User
	1,  // 19: sso.v1.SSO.GetSelfUser:output_type -> sso.v1.User
	2,  // 20: sso.v1.SSO.GetPublicKey:output_type -> sso.v1.PublicKey
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_sso_v1_sso_proto_init() }
func file_sso_v1_sso_proto_init() {
	if File_sso_v1_sso_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sso_v1_sso_proto_rawDesc), len(file_sso_v1_sso_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sso_v1_sso_proto_goTypes,
		DependencyIndexes: file_sso_v1_sso_proto_depIdxs,
		MessageInfos:      file_sso_v1_sso_proto_msgTypes,
	}.Build()
	File_sso_v1_sso_proto = out.File
	file_sso_v1_sso_proto_goTypes = nil
	file_sso_v1_sso_proto_depIdxs = nil
}
