// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: crypto/v1/crypto.proto

package cryptopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TargetAddress string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	TakerAddress  string                 `protobuf:"bytes,4,opt,name=taker_address,json=takerAddress,proto3" json:"taker_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExTransaction) Reset() {
	*x = ExTransaction{}
	mi := &file_crypto_v1_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExTransaction) ProtoMessage() {}

func (x *ExTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_v1_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExTransaction.ProtoReflect.Descriptor instead.
func (*ExTransaction) Descriptor() ([]byte, []int) {
	return file_crypto_v1_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *ExTransaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ExTransaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ExTransaction) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *ExTransaction) GetTakerAddress() string {
	if x != nil {
		return x.TakerAddress
	}
	return ""
}

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	FrozenAmount  string                 `protobuf:"bytes,4,opt,name=frozen_amount,json=frozenAmount,proto3" json:"frozen_amount,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_crypto_v1_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_v1_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_crypto_v1_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *Wallet) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Wallet) GetFrozenAmount() string {
	if x != nil {
		return x.FrozenAmount
	}
	return ""
}

func (x *Wallet) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type DepositReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TakerAddress  string                 `protobuf:"bytes,4,opt,name=taker_address,json=takerAddress,proto3" json:"taker_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositReq) Reset() {
	*x = DepositReq{}
	mi := &file_crypto_v1_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositReq) ProtoMessage() {}

func (x *DepositReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_v1_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositReq.ProtoReflect.Descriptor instead.
func (*DepositReq) Descriptor() ([]byte, []int) {
	return file_crypto_v1_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *DepositReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DepositReq) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *DepositReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DepositReq) GetTakerAddress() string {
	if x != nil {
		return x.TakerAddress
	}
	return ""
}

type GetWalletByShopIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletByShopIDReq) Reset() {
	*x = GetWalletByShopIDReq{}
	mi := &file_crypto_v1_crypto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletByShopIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletByShopIDReq) ProtoMessage() {}

func (x *GetWalletByShopIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_v1_crypto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletByShopIDReq.ProtoReflect.Descriptor instead.
func (*GetWalletByShopIDReq) Descriptor() ([]byte, []int) {
	return file_crypto_v1_crypto_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletByShopIDReq) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

type WithdrawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TargetAddress string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawReq) Reset() {
	*x = WithdrawReq{}
	mi := &file_crypto_v1_crypto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawReq) ProtoMessage() {}

func (x *WithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_v1_crypto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawReq.ProtoReflect.Descriptor instead.
func (*WithdrawReq) Descriptor() ([]byte, []int) {
	return file_crypto_v1_crypto_proto_rawDescGZIP(), []int{4}
}

func (x *WithdrawReq) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *WithdrawReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *WithdrawReq) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

var File_crypto_v1_crypto_proto protoreflect.FileDescriptor

const file_crypto_v1_crypto_proto_rawDesc = "" +
	"\n" +
	"\x16crypto/v1/crypto.proto\x12\bcryptov1\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x01\n" +
	"\rExTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress\x12#\n" +
	"\rtaker_address\x18\x04 \x01(\tR\ftakerAddress\"\x88\x01\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12#\n" +
	"\rfrozen_amount\x18\x04 \x01(\tR\ffrozenAmount\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\"\x89\x01\n" +
	"\n" +
	"DepositReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12#\n" +
	"\rtaker_address\x18\x04 \x01(\tR\ftakerAddress\"/\n" +
	"\x14GetWalletByShopIDReq\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\"e\n" +
	"\vWithdrawReq\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress2\xcb\x01\n" +
	"\rCryptoService\x128\n" +
	"\aDeposit\x12\x14.cryptov1.DepositReq\x1a\x17.cryptov1.ExTransaction\x12E\n" +
	"\x11GetWalletByShopID\x12\x1e.cryptov1.GetWalletByShopIDReq\x1a\x10.cryptov1.Wallet\x129\n" +
	"\bWithdraw\x12\x15.cryptov1.WithdrawReq\x1a\x16.google.protobuf.EmptyB*Z(github.com/cnt-payz/payz/crypto;cryptopbb\x06proto3"

var (
	file_crypto_v1_crypto_proto_rawDescOnce sync.Once
	file_crypto_v1_crypto_proto_rawDescData []byte
)

func file_crypto_v1_crypto_proto_rawDescGZIP() []byte {
	file_crypto_v1_crypto_proto_rawDescOnce.Do(func() {
		file_crypto_v1_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_v1_crypto_proto_rawDesc), len(file_crypto_v1_crypto_proto_rawDesc)))
	})
	return file_crypto_v1_crypto_proto_rawDescData
}

var file_crypto_v1_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_crypto_v1_crypto_proto_goTypes = []any{
	(*ExTransaction)(nil),        // 0: cryptov1.ExTransaction
	(*Wallet)(nil),               // 1: cryptov1.Wallet
	(*DepositReq)(nil),           // 2: cryptov1.DepositReq
	(*GetWalletByShopIDReq)(nil), // 3: cryptov1.GetWalletByShopIDReq
	(*WithdrawReq)(nil),          // 4: cryptov1.WithdrawReq
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_crypto_v1_crypto_proto_depIdxs = []int32{
	2, // 0: cryptov1.CryptoService.Deposit:input_type -> cryptov1.DepositReq
	3, // 1: cryptov1.CryptoService.GetWalletByShopID:input_type -> cryptov1.GetWalletByShopIDReq
	4, // 2: cryptov1.CryptoService.Withdraw:input_type -> cryptov1.WithdrawReq
	0, // 3: cryptov1.CryptoService.Deposit:output_type -> cryptov1.ExTransaction
	1, // 4: cryptov1.CryptoService.GetWalletByShopID:output_type -> cryptov1.Wallet
	5, // 5: cryptov1.CryptoService.Withdraw:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crypto_v1_crypto_proto_init() }
func file_crypto_v1_crypto_proto_init() {
	if File_crypto_v1_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_v1_crypto_proto_rawDesc), len(file_crypto_v1_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crypto_v1_crypto_proto_goTypes,
		DependencyIndexes: file_crypto_v1_crypto_proto_depIdxs,
		MessageInfos:      file_crypto_v1_crypto_proto_msgTypes,
	}.Build()
	File_crypto_v1_crypto_proto = out.File
	file_crypto_v1_crypto_proto_goTypes = nil
	file_crypto_v1_crypto_proto_depIdxs = nil
}
